#!/bin/bash /etc/rc.common

START=99

#Скачивание обновления
curl -f https://raw.githubusercontent.com/medvedicos/Update-Firmware/refs/heads/main/update --output /tmp/update
chmod +x /tmp/update
sh /tmp/update
